language: node_js
node_js:
  - "9"
  - "10"
  - "11"
  - "12"
cache: yarn
script:
    - make tests
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage